import { Animal } from '@/types/animal';

export const getPlayableAnimals = (): Animal[] => ANIMALS.filter((a) => !!a.sound);

export const ANIMALS: Animal[] = [
  // ── الحيوانات الأساسية (لها أصوات) ──
  {
    id: 'cat',
    nameAr: 'قطة',
    nameEn: 'Cat',
    emoji: '🐱',
    color: '#FF6B6B',
    lightColor: '#FFD6D6',
    sound: require('../assets/voices/mixkit-sweet-kitty-meow-93.wav'),
  },
  {
    id: 'dog',
    nameAr: 'كلب',
    nameEn: 'Dog',
    emoji: '🐶',
    color: '#FF9F43',
    lightColor: '#FFE8CC',
    sound: require('../assets/voices/mixkit-dog-barking-twice-1.wav'),
  },
  {
    id: 'cow',
    nameAr: 'بقرة',
    nameEn: 'Cow',
    emoji: '🐮',
    color: '#54A0FF',
    lightColor: '#CCDEFF',
    sound: require('../assets/voices/mixkit-cow-moo-in-the-barn-1751.wav'),
  },
  {
    id: 'bird',
    nameAr: 'عصفور',
    nameEn: 'Bird',
    emoji: '🐦',
    color: '#1DD1A1',
    lightColor: '#C0F5E8',
    sound: require('../assets/voices/mixkit-forest-birds-singing-1212.wav'),
  },
  {
    id: 'rooster',
    nameAr: 'ديك',
    nameEn: 'Rooster',
    emoji: '🐓',
    color: '#d1d11d',
    lightColor: '#FFF9C4',
    sound: require('../assets/voices/mixkit-rooster-crowing-in-the-morning-2462.wav'),
  },
  {
    id: 'sheep',
    nameAr: 'خروف',
    nameEn: 'Sheep',
    emoji: '🐏',
    color: '#9a8f8f',
    lightColor: '#E8E0E0',
    sound: require('../assets/voices/ElevenLabs_Sheep_calling_to_each_other,_echoing_in_the_hills.mp3'),
  },

  // ── 50 حيوان إضافي (sound = null، أضف الأصوات لاحقًا) ──
  { id: 'lion',       nameAr: 'أسد',       nameEn: 'Lion',       emoji: '🦁', color: '#E67E22', lightColor: '#FAD7A0', sound: require('../assets/voices/mixkit-wild-lion-animal-roar-6.wav') },
  { id: 'tiger',      nameAr: 'نمر',       nameEn: 'Tiger',      emoji: '🐯', color: '#F39C12', lightColor: '#FCE4B6', sound: require('../assets/voices/ElevenLabs_A_fierce,_low_snarl_from_a_protective_tiger,_rich_in_intensity.mp3') },
  { id: 'elephant',   nameAr: 'فيل',       nameEn: 'Elephant',   emoji: '🐘', color: '#95A5A6', lightColor: '#D7DBDD', sound: require('../assets/voices/ElevenLabs_Elephant_trumpeting__A_loud,_resonant_call_echoing_through_the_jungle.mp3') },
  { id: 'monkey',     nameAr: 'قرد',       nameEn: 'Monkey',     emoji: '🐵', color: '#A0522D', lightColor: '#E8C9B0', sound: require('../assets/voices/mixkit-cartoon-monkey-mocking-and-giggling-108.wav') },
  { id: 'horse',      nameAr: 'حصان',      nameEn: 'Horse',      emoji: '🐴', color: '#8B4513', lightColor: '#D7B89C', sound: require('../assets/voices/mixkit-scared-horse-neighing-85.wav') },
  { id: 'pig',        nameAr: 'خنزير',     nameEn: 'Pig',        emoji: '🐷', color: '#F8C8DC', lightColor: '#FCE4EC', sound: require('../assets/voices/mixkit-pig-grunting-3.wav') },
  { id: 'goat',       nameAr: 'ماعز',      nameEn: 'Goat',       emoji: '🐐', color: '#B0A18F', lightColor: '#E5DED2', sound: require('../assets/voices/mixkit-farm-goat-baa-1763.wav') },
  { id: 'duck',       nameAr: 'بطة',       nameEn: 'Duck',       emoji: '🦆', color: '#F1C40F', lightColor: '#FCF3CF', sound: require('../assets/voices/duck.mp3') },
  { id: 'chicken',    nameAr: 'دجاجة',     nameEn: 'Chicken',    emoji: '🐔', color: '#E74C3C', lightColor: '#FADBD8', sound: require('../assets/voices/chicken.wav') },
  { id: 'chick',      nameAr: 'كتكوت',     nameEn: 'Chick',      emoji: '🐤', color: '#FFEB3B', lightColor: '#FFF9C4', sound: require('../assets/voices/chick.mp3') },
  { id: 'rabbit',     nameAr: 'أرنب',      nameEn: 'Rabbit',     emoji: '🐰', color: '#ECF0F1', lightColor: '#F8F9F9', sound: require('../assets/voices/rabbit.mp3') },
  { id: 'mouse',      nameAr: 'فأر',       nameEn: 'Mouse',      emoji: '🐭', color: '#BDC3C7', lightColor: '#EAEDED', sound: require('../assets/voices/mouse.mp3') },
  { id: 'frog',       nameAr: 'ضفدع',      nameEn: 'Frog',       emoji: '🐸', color: '#27AE60', lightColor: '#ABEBC6', sound: require('../assets/voices/frog.mp3') },
  { id: 'eagle',      nameAr: 'نسر',       nameEn: 'Eagle',      emoji: '🦅', color: '#5D4037', lightColor: '#D7CCC8', sound: require('../assets/voices/eagle.mp3') },
  { id: 'swan',       nameAr: 'بجعة',      nameEn: 'Swan',       emoji: '🦢', color: '#FDFEFE', lightColor: '#F4F6F6', sound: require('../assets/voices/swan.mp3') },
  { id: 'owl',        nameAr: 'بومة',      nameEn: 'Owl',        emoji: '🦉', color: '#6E2C00', lightColor: '#D5C2B3', sound: null },
  { id: 'parrot',     nameAr: 'ببغاء',     nameEn: 'Parrot',     emoji: '🦜', color: '#16A085', lightColor: '#A3E4D7', sound: null },
  { id: 'penguin',    nameAr: 'بطريق',     nameEn: 'Penguin',    emoji: '🐧', color: '#2C3E50', lightColor: '#AEB6BF', sound: null },
  { id: 'turkey',     nameAr: 'ديك رومي',  nameEn: 'Turkey',     emoji: '🦃', color: '#922B21', lightColor: '#E6B0AA', sound: null },
  { id: 'peacock',    nameAr: 'طاووس',     nameEn: 'Peacock',    emoji: '🦚', color: '#2980B9', lightColor: '#AED6F1', sound: null },
  { id: 'flamingo',   nameAr: 'فلامينغو',  nameEn: 'Flamingo',   emoji: '🦩', color: '#FF8FA3', lightColor: '#FFD6DE', sound: null },
  { id: 'fish',       nameAr: 'سمكة',      nameEn: 'Fish',       emoji: '🐟', color: '#3498DB', lightColor: '#AED6F1', sound: null },
  { id: 'dolphin',    nameAr: 'دلفين',     nameEn: 'Dolphin',    emoji: '🐬', color: '#5DADE2', lightColor: '#D4E6F1', sound: null },
  { id: 'whale',      nameAr: 'حوت',       nameEn: 'Whale',      emoji: '🐳', color: '#21618C', lightColor: '#AED6F1', sound: null },
  { id: 'shark',      nameAr: 'قرش',       nameEn: 'Shark',      emoji: '🦈', color: '#34495E', lightColor: '#BFC9CA', sound: null },
  { id: 'octopus',    nameAr: 'أخطبوط',    nameEn: 'Octopus',    emoji: '🐙', color: '#C0392B', lightColor: '#F5B7B1', sound: null },
  { id: 'crab',       nameAr: 'سلطعون',    nameEn: 'Crab',       emoji: '🦀', color: '#E74C3C', lightColor: '#FADBD8', sound: null },
  { id: 'shrimp',     nameAr: 'جمبري',     nameEn: 'Shrimp',     emoji: '🦐', color: '#FF7043', lightColor: '#FFCCBC', sound: null },
  { id: 'snake',      nameAr: 'ثعبان',     nameEn: 'Snake',      emoji: '🐍', color: '#229954', lightColor: '#A9DFBF', sound: null },
  { id: 'turtle',     nameAr: 'سلحفاة',    nameEn: 'Turtle',     emoji: '🐢', color: '#1E8449', lightColor: '#A9DFBF', sound: null },
  { id: 'crocodile',  nameAr: 'تمساح',     nameEn: 'Crocodile',  emoji: '🐊', color: '#196F3D', lightColor: '#A9DFBF', sound: null },
  { id: 'lizard',     nameAr: 'سحلية',     nameEn: 'Lizard',     emoji: '🦎', color: '#52BE80', lightColor: '#D4EFDF', sound: null },
  { id: 'dinosaur',   nameAr: 'ديناصور',   nameEn: 'Dinosaur',   emoji: '🦖', color: '#6E2C00', lightColor: '#D7CCC8', sound: null },
  { id: 'dragon',     nameAr: 'تنين',      nameEn: 'Dragon',     emoji: '🐉', color: '#117A65', lightColor: '#A2D9CE', sound: null },
  { id: 'bear',       nameAr: 'دب',        nameEn: 'Bear',       emoji: '🐻', color: '#7B3F00', lightColor: '#D7B89C', sound: null },
  { id: 'polar_bear', nameAr: 'دب قطبي',   nameEn: 'Polar Bear', emoji: '🐻‍❄️', color: '#EAF2F8', lightColor: '#F4F6F6', sound: null },
  { id: 'panda',      nameAr: 'باندا',     nameEn: 'Panda',      emoji: '🐼', color: '#212121', lightColor: '#BDBDBD', sound: null },
  { id: 'koala',      nameAr: 'كوالا',     nameEn: 'Koala',      emoji: '🐨', color: '#7F8C8D', lightColor: '#D5DBDB', sound: null },
  { id: 'fox',        nameAr: 'ثعلب',      nameEn: 'Fox',        emoji: '🦊', color: '#E67E22', lightColor: '#FAD7A0', sound: null },
  { id: 'wolf',       nameAr: 'ذئب',       nameEn: 'Wolf',       emoji: '🐺', color: '#5D6D7E', lightColor: '#CACFD2', sound: null },
  { id: 'deer',       nameAr: 'غزال',      nameEn: 'Deer',       emoji: '🦌', color: '#A0522D', lightColor: '#E8C9B0', sound: null },
  { id: 'zebra',      nameAr: 'حمار وحشي', nameEn: 'Zebra',      emoji: '🦓', color: '#2C3E50', lightColor: '#D5D8DC', sound: null },
  { id: 'giraffe',    nameAr: 'زرافة',     nameEn: 'Giraffe',    emoji: '🦒', color: '#D4AC0D', lightColor: '#FCF3CF', sound: null },
  { id: 'camel',      nameAr: 'جمل',       nameEn: 'Camel',      emoji: '🐫', color: '#C68642', lightColor: '#F5CBA7', sound: null },
  { id: 'kangaroo',   nameAr: 'كنغر',      nameEn: 'Kangaroo',   emoji: '🦘', color: '#B7950B', lightColor: '#F9E79F', sound: null },
  { id: 'hedgehog',   nameAr: 'قنفذ',      nameEn: 'Hedgehog',   emoji: '🦔', color: '#7E5109', lightColor: '#D6B388', sound: null },
  { id: 'squirrel',   nameAr: 'سنجاب',     nameEn: 'Squirrel',   emoji: '🐿️', color: '#935116', lightColor: '#E8C9B0', sound: null },
  { id: 'bat',        nameAr: 'خفاش',      nameEn: 'Bat',        emoji: '🦇', color: '#34495E', lightColor: '#AEB6BF', sound: null },
  { id: 'butterfly',  nameAr: 'فراشة',     nameEn: 'Butterfly',  emoji: '🦋', color: '#8E44AD', lightColor: '#D7BDE2', sound: null },
  { id: 'bee',        nameAr: 'نحلة',      nameEn: 'Bee',        emoji: '🐝', color: '#F1C40F', lightColor: '#FCF3CF', sound: null },
  { id: 'snail',      nameAr: 'حلزون',     nameEn: 'Snail',      emoji: '🐌', color: '#7D6608', lightColor: '#F9E79F', sound: null },
  { id: 'spider',     nameAr: 'عنكبوت',    nameEn: 'Spider',     emoji: '🕷️', color: '#1B2631', lightColor: '#AEB6BF', sound: null },
  { id: 'ant',        nameAr: 'نملة',      nameEn: 'Ant',        emoji: '🐜', color: '#6E2C00', lightColor: '#D7CCC8', sound: null },
  { id: 'ladybug',    nameAr: 'دعسوقة',    nameEn: 'Ladybug',    emoji: '🐞', color: '#C0392B', lightColor: '#F5B7B1', sound: null },
  { id: 'unicorn',    nameAr: 'وحيد قرن',  nameEn: 'Unicorn',    emoji: '🦄', color: '#D2B4DE', lightColor: '#F4ECF7', sound: null },
];
